name: Build Android
on:
  workflow_dispatch: {}

jobs:
  Build_Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Generate keystore
        run: |
          keytool -genkeypair -v -keystore release-key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias release \
          -dname "CN=MetallicAllex, OU=MetaDev, O=MetaDeveloper, L=China, ST=Unknown, C=CN" \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }}

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
