name: Build Android
on:
  workflow_dispatch: {}

jobs:
  Build_Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Java 17 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.12'
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Generate keystore
        run: |
          keytool -genkeypair -v -keystore release-key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias release \
          -dname "CN=MetallicAllex, OU=MetaDev, O=MetaDeveloper, L=China, ST=Unknown, C=CN" \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }}

      - name: Create key.properties file
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=release" >> android/key.properties
          echo "storeFile=release-key.jks" >> android/key.properties
        
      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
