name: Build Android
run-name: Build Android
on:
  workflow_dispatch: {}
jobs:
  Build_Android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # 设置 Java 17 环境
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 设置 Flutter 环境
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # 解码并生成 keystore 文件
    - name: Decode keystore
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/release-key.jks

    # 创建 key.properties 文件
    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=release-key.jks" >> android/key.properties

    # 安装依赖
    - run: flutter pub get

    # 构建 Android APK
    - run: flutter build apk --release

    # 上传 APK 文件作为构建工件
    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
